function cpiImport = cpiImport(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CPIIMPORT = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a timetable.
%
%  CPIIMPORT = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  cpiImport = importfile("/MATLAB Drive/FPCPITOTLZGCAN.csv", [2, Inf]);
%
%  See also READTIMETABLE.
%
% Auto-generated by MATLAB on 12-Apr-2024 12:48:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
fname = char(filename);
opts.VariableNames = ["DATE", fname(1:14)];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd", "DatetimeFormat", "preserveinput");

% Import the data
cpiImport = readtimetable(filename, opts, "RowTimes", "DATE");

end